version: '3'

services:
  ipfs_node:
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"  # IPFS Swarm Port
      - "5001:5001"  # IPFS API Port
      - "8080:8080"  # IPFS Gateway Port
    volumes:
      - ipfs_data:/data/ipfs
    command: ["daemon", "--migrate=true"]

volumes:
  ipfs_data: